### PR TITLE
simplify NewCollectionSizeCollector

### PR DESCRIPTION
**Pull request by rogpeppe**
The NewStatsGetter function seems unnecessary - if we pass
in the collection directly, the session can be inferred from
that and copied as necessary.

This also means that we aren't exporting functions that return
and/or take unexported types.

### CODE REVIEW

**Comment by mhilton** [comment]
As you're changing the interface anyway I think you could probably go further. It seems to me that it would be rather nice if this could be used for multiple collections at once (somewhat like a gauge vector https://godoc.org/github.com/prometheus/client_golang/prometheus#GaugeVec) Also if you didn't copy the incoming Session at creation time you wouldn't need to have a Close method. I think that would be an overall win for simplicity.

**Comment by rogpeppe** [comment]
I didn't want to increase the scope too much, just make the existing implementation simpler - a multiple-collection collector would be nice, but not here.

I think the reason we want to copy the session is that we want things to work even when the original session has been closed, and I suspect that if you Copy a closed session you'll get a panic.

**Comment by mattyw** [comment]
LGTM

**Comment by mhilton** [comment]
:+1:

**Pull request merged**
